export const lorem = [
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius illum assumenda suscipit? Eius illum dicta ipsam quibusdam quae, magnam iure ex earum eum laborum, illo officiis consequatur voluptates laboriosam. Repellendus architecto mollitia repellat laudantium dolorem culpa voluptates soluta optio nostrum?'
];
